### PR TITLE
fix: remove defunct sample explorer

### PR DESCRIPTION
**Pull request by ianhi**
SampleExplorer was removed in: https://github.com/pymmcore-plus/pymmcore-widgets/pull/139

need to also remove it here. Also seems as though some recent changes in useq have led to mypy issues

### CODE REVIEW

**Comment by ianhi** [comment]
huh. locally I got these mypy errors, but not here it seems:

```
src/napari_micromanager/_saving.py:86: error: Argument 1 to "len" has
incompatible type
"Union[MultiPhaseTimePlan, TIntervalDuration, TIntervalLoops, TDurationLoops, None]";
expected "Sized"  [arg-type]
                    if len(sequence.time_plan) == 0
                           ^~~~~~~~~~~~~~~~~~
src/napari_micromanager/_saving.py:109: error: Argument 1 to "len" has
incompatible type
"Union[MultiPhaseTimePlan, TIntervalDuration, TIntervalLoops, TDurationLoops, None]";
expected "Sized"  [arg-type]
    ...      ax = sequence.axis_order.index("p") if len(sequence.time_plan) >...
                                                        ^~~~~~~~~~~~~~~~~~
Found 2 errors in 1 file (checked 1 source file)
```

**Comment by ianhi** [comment]
I think merging this will allow https://github.com/pymmcore-plus/napari-micromanager/pull/258 to be merged also

**Review by tlambert03 — APPROVED** [review]
thanks @ianhi!

**Comment by tlambert03** [comment]
> huh. locally I got these mypy errors, but not here it seems:

yep, these are valid... looks like pre-commit is perhaps using a cached environment.  Will fix elsewhere

**Pull request merged**
