### PR TITLE
test: fix tests, stop using make_napari_viewer fixture

### PR DESCRIPTION
**Pull request by fdrgsp**
add `pytest.mark.enable_console`

### CODE REVIEW

**Comment by tlambert03** [comment]
I see this one remaining test fail a lot too.  Usually if I rerun it it goes away (will try now), but any idea what's going on there?

**Comment by tlambert03** [comment]
Just curious, were you able to figure out where/when this marker got added in napari?

**Comment by fdrgsp** [comment]
> Just curious, were you able to figure out where/when this marker got added in napari?

Nope, not sure what changed in napari's last week release that affected this behavior (for sure not the `make_napari_viewer` method though, it has not been recently modified)...

**Comment by tlambert03** [comment]
for my tastes, this fix is to specific to something that napari is internally doing in their tests, and may well break again in the future.  I just think we shouldn't be using `make_napari_viewer`... will update

**Comment by tlambert03** [comment]
pushed a change that stops using make_napari_viewer

**Pull request merged**
