### PR TITLE
Add a widget to create pixel size configurations

### PR DESCRIPTION
**Pull request by fdrgsp**
This might be a temporary solution to set the pixel size. As @tlambert03 mentioned in #136 (I'm adding a `Micro-Manager` menu...), this widget could be placed in the menu and the user can define pixel size configs from there.

What do you think?

https://user-images.githubusercontent.com/70725613/157528636-7246d51a-b879-4e2e-83d0-857bacb75f56.mov

### CODE REVIEW

**Comment by fdrgsp** [comment]
> What happens if you click `new row`? Am I right that in most cases there will only be one combobox of objectives? If that's the case then I think we should just display all the rows at once and you click around to choose which ones to edit.

@ianhi it's just my opinion but I think we should make the user decide how to set the configuration...in some cases they can add some optical components in the path that will be used only with a specific objective, etc...

**Comment by tlambert03** [comment]
is it possible to directly modify image pixel size?  (doesn't look like it is yet).  I don't think the user should be "forced" to use the camera pixel/mag math...  If they know their image pixel size (which is the default interface in micromanager right?)  they should be allowed to enter it

**Comment by fdrgsp** [comment]
@tlambert03 I think everything is working as it should now...

**Comment by fdrgsp** [comment]
closing since it has been moved to https://github.com/pymmcore-plus/pymmcore-widgets.

**Comment by tlambert03** [comment]
did this feature specifically get implemented?  If not, we shouldn't close the issue (but we can transfer it)

**Comment by fdrgsp** [comment]
@tlambert03  yes sorry, I've added it to [pymmcore-widgets](https://github.com/pymmcore-plus/pymmcore-widgets).

**Comment by tlambert03** [comment]
Can you link the pr here so we can see it?

**Comment by fdrgsp** [comment]
@tlambert03 #141

**Comment by tlambert03** [comment]
:joy: ... that links to _this_ PR.  looking through your history, I'm guessing it was https://github.com/pymmcore-plus/pymmcore-widgets/pull/6

If I recall, there were definitely some UI and organization-related questions remaining to be answered in this PR.  Let's not merge un-discussed, un-reviewed things into the new repo.  🙏

**Comment by fdrgsp** [comment]
😂 sorry I didn't get that. yes that's the one. do you want me to reopen it in [pymmcore-widgets](https://github.com/pymmcore-plus/pymmcore-widgets)?

**Comment by tlambert03** [comment]
No, just create issues reminding us as a group to evaluate them

**Pull request closed without merging**
