### PR TITLE
[WIP]MDA to Sample Explorer

### PR DESCRIPTION
**Pull request by fdrgsp**
This PR adds `mda` capabilities to the `Sample Explorer`. 

It requires https://github.com/tlambert03/useq-schema/pull/44.

Screen Shot 2022-06-27 at 7 10 16 PM

It is now possible to perform:
 - time-lapses (`Time`)
 - z-stacks (`Z-Stacks`)
 - multiple  RxC grids by selecting different starting positions (`Grid Starting Positions`)

### CODE REVIEW

**Comment by fdrgsp** [comment]
texts are failing because of https://github.com/tlambert03/useq-schema/pull/44.

**Comment by CedricEsp** [comment]
Hi @fdrgsp , when I tried the PR with a 5x5. 0% overlap, for some reason the middle tile was dark:
Screen Shot 2022-07-05 at 11 03 23 AM
Also, I think it would be great to stack the position in one grid.

**Comment by fdrgsp** [comment]
Hi @CedricEsp,

> Hi @fdrgsp , when I tried the PR with a 5x5. 0% overlap, for some reason the middle tile was dark:
 If you toggle the layers off and on again, you will see the image (I guess there is a small issue with the zarr and napari, I have to look into that).

> Also, I think it would be great to stack the position in one grid.

What do you mean by "stack the position in one grid"? Like having all the layers in a single stack without translation?

**Comment by CedricEsp** [comment]
> What do you mean by "stack the position in one grid"? Like having all the layers in a single stack without translation?

Indeed, not having one layer per position but only one per grid.

**Comment by fdrgsp** [comment]
> not having one layer per position but only one per grid

Hey @CedricEsp, just to make sure I understand...you would prefer a single grid layer with a stitched image of all the positions or a single grid layer as a stack?

**Comment by CedricEsp** [comment]
Personally, I would prefer a single grid layer as a stack with an option to stitch the images together (maybe through a separate napari hub plugin?)

**Comment by fdrgsp** [comment]
@CedricEsp 

> Personally, I would prefer a single grid layer as a stack

I just added a `checkbox` to display the scan as a single stack. Let me know if this is what you were looking for :)

**Comment by CedricEsp** [comment]
@fdrgsp it looks great!

**Pull request closed without merging**
